#!/usr/bin/env python
# encoding=utf-8

"""Simple TCP/IP proxy for libnotify.

This program lets you send pop-up notifications from remote servers to your
workstation.  You start this program then connect to a remote server using SSH,
having port 8111 forwarded back to you, then you send messages to that port.
See the README.markdown file for details.
"""

import socket

import pynotify


HOST = "localhost"
PORT = 8111


def serve():
    srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    srv.bind((HOST, PORT))
    srv.listen(5)

    #print "Listening for messages on %s:%u" % (HOST, PORT)

    try:
        while True:
            (client, address) = srv.accept()
            #print "Incoming connection from %s:%s" % address

            data = ""
            while True:
                tmp = client.recv(1024)
                if not tmp:
                    break
                data += tmp

            parts = data.strip().decode("utf-8").split("\n")
            if len(parts) >= 2:
                pynotify.Notification(parts[0], parts[1], "dialog-warning").show()

            client.close()
    except KeyboardInterrupt:
        srv.close()
        #print "Terminated."
            

if __name__ == "__main__":
    serve()
