application: dead-channel-news
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /google4c14bfd1bdbab0dd.html
  static_files: static/google4c14bfd1bdbab0dd.html
  upload: static/google4c14bfd1bdbab0dd.html
- url: /static/
  static_dir: static

- url: /
  script: handlers.py
- url: /all.ics
  script: handlers.py
- url: /cron/hourly
  script: handlers.py
  login: admin
- url: /cron/daily
  script: handlers.py
  login: admin
- url: /feedback
  script: handlers.py
- url: /list.csv
  script: handlers.py
  login: admin
- url: /notify
  script: handlers.py
  login: admin
- url: /now
  script: handlers.py
- url: /rss.xml
  script: handlers.py
- url: /submit
  script: handlers.py
  login: admin
- url: /subscribe
  script: handlers.py
