application: dead-channel-news
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: news.py
- url: /import
  script: news.py
- url: /node/\d+
  script: news.py
- url: /submit
  script: news.py

- url: /static/
  static_dir: static
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
